NAME = ClipboardPasteInputDevice
TYPE = SHARED
APP_MIME_SIG =
SRCS = InputDevice.cpp
RDEFS = InputDevice.rdef
RSRCS =
LIBS= be
LIBPATHS=
SYSTEM_INCLUDE_PATHS =
LOCAL_INCLUDE_PATHS =
OPTIMIZE=
LOCALES=
DEFINES=
WARNINGS =
SYMBOLS =
DEBUGGER =
COMPILER_FLAGS = -Wall -Wno-multichar
LINKER_FLAGS =
APP_VERSION =
DRIVER_PATH =
INSTALL_DIR = /boot/system/non-packaged/add-ons/input_server/devices

## include the makefile-engine
DEVEL_DIRECTORY := \
	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)
include $(DEVEL_DIRECTORY)/etc/makefile-engine
